### ISSUE TITLE
Error: Cannot find module 'C:\scripts\install.js'

### ISSUE THREAD

**Issue by itsecurityco** [shama/nodewebkit#49]
Hello, I'm trying to install nodewebkit and I got the following error. I have the latest node.js version installed. Any help? thanks :)

node.js version: 0.10.31
npm: 1.4.23

```
C:\>npm install nodewebkit
|
> nodewebkit@0.10.4 postinstall C:\node_modules\nodewebkit
> node scripts/install.js


module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\scripts\install.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
npm ERR! nodewebkit@0.10.4 postinstall: `node scripts/install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the nodewebkit@0.10.4 postinstall script.
npm ERR! This is most likely a problem with the nodewebkit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodewebkit
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
 "nodewebkit"
npm ERR! cwd C:\
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\npm-debug.log
npm ERR! not ok code 0

```

**Comment by AndersBillLinden** [comment]
How will "take a look on my windows box" help me? A random person that did a google search? :)

**Comment by shama** [comment]
@AndersBillLinden Because you'll realize my comment is nearly 3 years old and then get fed up waiting for me to find a solution to your issue. So you'll fire up your own windows box, look into the problem, discover the solution, write a patch that fixes it and become the hero of every other random googler landing on this issue.
