### ISSUE TITLE
Unable to install nodewebkit@0.10.5

### ISSUE THREAD

**Issue by agirorn** [shama/nodewebkit#61]
I am unable to install nodewebkit 0.10.5 on Ubuntu Linux.I previously reported this in nwjs/npm-installer/issues/52

```shell
my-app git:(master) npm install nodewebkit@0.10.5

> nodewebkit@0.10.5 postinstall /home/agirorn/code/my-app/node_modules/nodewebkit
> node scripts/install.js

stream.js:74
      throw er; // Unhandled stream error in pipe.0.5-linux-x64.tar.gz [          ] 0 %
      ^

Error: invalid tar file
    at Extract.Parse._startEntry (/home/agirorn/code/my-app/node_modules/tar/lib/parse.js:145:13)
    at Extract.Parse._process (/home/agirorn/code/my-app/node_modules/tar/lib/parse.js:127:12)
    at BlockStream.<anonymous> (/home/agirorn/code/my-app/node_modules/tar/lib/parse.js:47:8)
    at emitOne (events.js:77:13)
    at BlockStream.emit (events.js:169:7)
    at BlockStream._emitChunk (/home/agirorn/code/my-app/node_modules/block-stream/block-stream.js:145:10)
    at BlockStream.resume (/home/agirorn/code/my-app/node_modules/block-stream/block-stream.js:58:15)
    at Extract.Reader.resume (/home/agirorn/code/my-app/node_modules/fstream/lib/reader.js:255:34)
    at DirWriter.<anonymous> (/home/agirorn/code/my-app/node_modules/tar/lib/extract.js:57:8)
    at emitNone (events.js:67:13)
npm WARN @nls/technician-app@0.7.0 No repository field.
npm WARN @nls/technician-app@0.7.0 No license field.
npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/home/agirorn/.nvm/versions/node/v4.7.0/bin/node" "/home/agirorn/.nvm/versions/node/v4.7.0/bin/npm" "install" "nodewebkit@0.10.5"
npm ERR! node v4.7.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! nodewebkit@0.10.5 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodewebkit@0.10.5 postinstall script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodewebkit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodewebkit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodewebkit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/agirorn/code/my-app/npm-debug.log
➜  my-app git:(master) 
```

Can the installer for nodewebkit@0.10.5 be fixed to support redirect, or can http://dl.node-webkit.org be changed in a way that it serves the files needed to install nodewebkit instead of redirecting to http://dl.nwjs.io so that the installer continues to work as expected?

**Comment by glauserr** [comment]
The same problem! Please redirect the installer to http://dl.nwjs.io It would safe a lot of time!!

**Comment by shama** [comment]
This project is deprecated and will not be updated. Please use `npm install nw`. If you can't use `nw` then you'll need to manually download the executable yourself from the website or fork the script from this repo and have it do whatever your heart desires.
